version: 0.2

run-as: root

phases:
  install:
    commands:
      - # install terraform binary
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  pre_build:
    commands:
      - echo executing pre build phase
      - terraform init
      - terraform destroy --auto-approve
  build:
    commands:
      - echo executing build phase
      - terraform apply --auto-approve
  post_build:
    commands:
      - echo executing post build phase