version: 0.2

run-as: root

phases:
  install:
    commands:
      - echo executing install phase
      - apt-get update && \
        apt-get install -y -q --allow-unauthenticated \
        software-properties-common \
        git \
        curl \
        zip \
        jq \
        boxes \
        wget \
        sudo
      # Install Terraform
      - curl https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_386.zip -o terraform_1.3.6_linux_386.zip \
        && unzip terraform_1.3.6_linux_386.zip \
        && chmod +x terraform \
        && mv terraform /usr/local/bin \
        && rm -f terraform_1.3.6_linux_386.zip \
        && terraform --version
  pre_build:
    commands:
      - echo executing pre build phase
  build:
    commands:
      - echo executing build phase
  post_build:
    commands:
      - echo executing post build phase